### ISSUE TITLE
MatplotlibDeprecationWarning in executable

### ISSUE THREAD

**Issue by jlplenio** [bovheat/bovheat#13]
During executable boot up:
> The MATPLOTLIBDATA environment variable was deprecated in Matplotlib 3.1 and will be removed in 3.3.

Known issue:
https://github.com/pyinstaller/pyinstaller/issues/3959

Solutions - shall we suppress or downgrade?
https://stackoverflow.com/questions/57517371/matplotlibdeprecationwarning-with-pyinstaller-exe

**Comment by ndevln** [comment]
Down grade ist doof. Ist etwas hacks, aber ist ja nicht für immer. 

```
import warnings 
warnings.filterwarnings("ignore", "(?s).*MATPLOTLIBDATA.*", category=UserWarning)
```
